"""empty message

Revision ID: 4830619f31a7
Revises: 0a2d1a26ee6c
Create Date: 2023-08-08 01:00:21.710958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4830619f31a7'
down_revision = '0a2d1a26ee6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_communities',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'community_id')
    )
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('followed_id')
        batch_op.drop_column('follower_id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'communities', ['community_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('community_id')

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('followed_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['follower_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['followed_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    op.drop_table('user_communities')
    # ### end Alembic commands ###